// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIV.Data;

#nullable disable

namespace PIV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PIV.Models.Weather", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Humidity")
                        .HasColumnType("float");

                    b.Property<DateTime>("InfoDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Precipitation")
                        .HasColumnType("float");

                    b.Property<float>("TemperatureC")
                        .HasMaxLength(4)
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
